slurm:
  name:
    - eval:sys.argv[0][:-3].split('/')[-1]
    - ${slurm.train.noise}
    - ${data.fdset}
    - orig
    - ${data.tdset}
    - ${train.lr}
    - ${train.seed}

train:
  arch: fconv_classifier
  num_classes: 2
  lr: 1e-03
  lr_scheduler: inverse_sqrt
  warmup_updates: 500
  max_sentences: 8
  update_freq: 4
  max_positions: ~
  max_epoch: ~ 
  skip_invalid_size_inputs_valid_test: true
  encoder_layers: ~

data:
  bin: orig
  num_sents: 200000
