slurm:
  job_name:
    - eval:sys.argv[0][:-3].split('/')[-1]
    - ${data.fdset}
    - orig_reg
    - ${data.tdset}
    - ${train.seed}

train:
  arch: lstm_classifier
  num_classes: 1
  lr: 1e-03
  lr_scheduler: inverse_sqrt
  warmup_updates: 500
  max_epoch: 20
  max_sentences: 8
  update_freq: 4
  max_positions: ~
  skip_invalid_size_inputs_valid_test: true
  encoder_layers: 3
  regression_target: true
  best_checkpoint_metric: loss
  maximize_best_checkpoint_metric: false

data:
  bin: orig.reg
  num_sents: 100000

eval:
  model:
    date: 2020-04-01
    name:
      - launch_train
      - ${data.fdset}
      - orig_reg
      - ${train.seed}
    bin: orig
    data: aws
  data: aws

display:
  dir: 
    date: 2020-04-03
    name:
      - eval_roberta_glue
      - ???
      - ???
      - orig_reg
      - ???
      - ???
