defaults:
  - hydra/launcher: slurm

hydra:
  run:
    dir: /h/nng/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
  sweep:
    dir: /h/nng/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
    subdir: ${hydra.job.num}

venv: robust
wait: false
extra: ~
next_day: ~
max_running: -1
max_pending: -1

data:
  bin: orig
  num_sents: ~

slurm:
  cpus_per_task: eval:4*int("${slurm.gres}"[-1])
  dependency: ~
  exclude: gpu107,gpu080,gpu117
  gres: gpu:1
  job_name:
    - eval:sys.argv[0][:-3].split('/')[-1]
    - ${data.fdset}
    - ${data.bin}
    - ${data.tdset}
    - ${gen.shard}
    - ${train.seed}
    - ${extra}
  mem: eval:str(22*int("${slurm.gres}"[-1]))+'G'
  nodes: 1
  ntasks_per_node: 1
  open_mode: append
  partition: gpu
  account: ~
  qos: normal

train:
  adam_betas: (0.9, 0.98)
  adam_eps: 1.0e-06
  arch: ~
  best_checkpoint_metric: accuracy
  clip_norm: 0.0
  criterion: sentence_prediction
  ddp_backend: no_c10d
  dropout: 0.1
  find_unused_parameters: true
  word_dropout_prob: ~
  fp16: true
  init_token: 0
  input0_mask: false
  input1_mask: false
  keep_interval_updates: 1
  keep_last_epochs: 1
  leave_unmasked_prob: 0.0
  log_interval: 10
  lr: 1.0e-05
  lr_scheduler: polynomial_decay
  mask_prob: 0.0
  max_epoch: 10
  max_positions: 512
  max_sentences: ~
  max_tokens: 4400
  max_updates: ~
  maximize_best_checkpoint_metric: true
  num_classes: ~
  optimizer: adam
  ordinal: false
  random_token_prob: 0.0
  regression_target: false
  required_batch_size_multiple: 1
  save_interval_updates: ~
  seed: ~
  separator_token: 2
  skip_invalid_size_inputs_valid_test: true
  augment: ~
  src_temperature: ~
  tgt_temperature: ~
  soft_labels: false
  task: sentence_prediction
  update_freq: 1

eval:
  inpu0_mask: false
  input1_mask: false
  levae_unmasked_prob: 0.0
  mask_prob: 0.0
  random_token_prob: 0.0
  reconstruct: false
  weighted: false
  split: valid
  model: 
    date: ~
    name: 
      - launch_train
      - ${data.fdset}
      - ${data.bin}
      - ${train.seed}
      - ${extra}
    bin: ${data.bin}

display:
  compare:
    date: ~
    no_seed: true
    bin: orig
  dir:
    date: ~
    name: 
      - eval_roberta_glue
      - ~
      - ~
      - ${data.bin}
      - ~
      - ~
      - ~

gen:
  batch: 8
  depth: 1
  dset: ${data.bin}
  in_dset: ${gen.model.bin}
  label_samples: 1
  leave_unmasked_prob: 0.1
  mask_prob: 0.15
  max_tries: 1000
  metropolis: false
  num_samples: 5
  num_shards: 8
  progressive: false
  random_token_prob: 0.1
  shard: ~
  sort: false
  topk: -1
  recon: base
  seed: ~
  model:
    date: ~
    name: 
      - launch_train
      - ${data.fdset}
      - ${gen.model.bin}
      - ${gen.model.seed}
      - ${extra}
    bin: ~
    seed: ~

